import { defineConfig } from 'vitepress'
import { echartsPlugin } from './plugins/echarts-plugin'
import { mermaidPlugin } from './plugins/mermaid-plugin'
import { readdirSync, readFileSync, statSync } from 'fs'
import { join, resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { tmpdir } from 'os'
import taskLists from 'markdown-it-task-lists'

const __dirname = dirname(fileURLToPath(import.meta.url))

const srcDir = process.env.MCP_SRC_DIR
  ?? resolve(__dirname, '../{{cookiecutter.project_slug}}/docs/example-minimal')
const outDir = process.env.MCP_OUT_DIR
  ?? resolve(__dirname, '../dist')

function extractTitle(content: string): string | undefined {
  const fm = content.match(/^---\s*\n([\s\S]*?)\n---/)
  if (fm) {
    const m = fm[1].match(/^title:\s*(.+)$/m)
    if (m) return m[1].trim()
  }
  for (const line of content.replace(/^---[\s\S]*?---/, '').split('\n')) {
    const t = line.trim()
    if (t.startsWith('# ') && !t.startsWith('## ')) return t.slice(2).trim()
  }
}

function generateSidebarItems(dir: string, base: string) {
  try {
    return readdirSync(dir)
      .filter(f => f.endsWith('.md') && f !== 'index.md' && statSync(join(dir, f)).isFile())
      .sort()
      .map(f => {
        const title = extractTitle(readFileSync(join(dir, f), 'utf-8'))
        const m = f.match(/^(\d+)-/)
        const n = m ? parseInt(m[1], 10) : null
        return {
          text: n ? `${n}. ${title ?? f.replace('.md', '')}` : (title ?? f.replace('.md', '')),
          link: base + f.replace('.md', '')
        }
      })
  } catch {
    return []
  }
}

function siteTitle(): string {
  const idx = join(srcDir, 'index.md')
  try { return extractTitle(readFileSync(idx, 'utf-8')) ?? 'Documentation' }
  catch { return 'Documentation' }
}

export default defineConfig({
  srcDir,
  outDir,
  title: siteTitle(),
  description: 'Generated by markdown-chartpress',
  lang: 'en-US',

  vite: {
    cacheDir: join(tmpdir(), 'mkpress-vite-cache'),
  },

  themeConfig: {
    outline: { level: [2, 4], label: 'On this page' },
    search: { provider: 'local' },
    sidebar: [{ text: siteTitle(), items: generateSidebarItems(srcDir, '/') }],
    docFooter: { prev: 'Previous', next: 'Next' },
    lastUpdated: { text: 'Last updated' },
  },

  markdown: {
    lineNumbers: false,
    config: (md) => {
      md.use(echartsPlugin)
      md.use(mermaidPlugin)
      md.use(taskLists, { enabled: true })
    }
  }
})
